Build Linux:
  image: nexus.barrage.net:13455/barrage-internal/electronjs-builder
  script:
    - cp -R ./ /project
    - cd /project
    - npm install --only=prod --no-package-lock
    - npm run electron:build --linux
  tags:
    - docker-executor
  artifacts:
    paths:
      - dist_electron/*.AppImage
      - dist_electron/*.deb

Build MacOS:
  script:
    - source ~/.zshrc
    - WORKDIR=$(mktemp -d)
    - rsync -r --exclude=.git ./ "$WORKDIR"
    - cd "$WORKDIR"
    - npm install
    - npm run electron:build --mac
    - ls dist_electron
  tags:
    - macos-electronjs
  artifacts:
    paths:
      - /"$WORKDIR"/dist_electron/*.dmg
      - /"$WORKDIR"/dist_electron/*.pkg
