Build Linux:
  image: nexus.barrage.net:13455/barrage-internal/electronjs-builder
  script:
    - cp -R ./ /project
    - cd /project
    - npm install --only=prod --no-package-lock
    - npm run electron:build --linux
  tags:
    - docker-executor
  artifacts:
    paths:
      - dist_electron/*.AppImage
      - dist_electron/*.deb

Build MacOS:
  script:
    - source ~/.zshrc
    - npm run clean-post
    - rsync -r --exclude=.git ./ /Users/barrage/projects/vue-electronjs
    - cd /Users/barrage/projects/vue-electronjs
    - npm install --only=prod --no-package-lock
    - npm run electron:build --mac
    - npm run clean-post
  tags:
    - macos-electronjs
  artifacts:
    paths:
      - /Users/barrage/projects/vue-electronjs/dist_electron/*.dmg
      - /Users/barrage/projects/vue-electronjs/dist_electron/*.pkg
