Build Linux:
  image: nexus.barrage.net:13455/barrage-internal/electronjs-builder
  script:
    - apt-get update ; apt-get --yes install rsync
    - cp -R ./ /project
    - cd /project
    - npm install --only=prod --no-package-lock
    - npm run electron:build --linux
    - cd $CI_PROJECT_DIR
    - rsync -r /project/dist_electron ./
  tags:
    - docker-executor
  artifacts:
    paths:
      - dist_electron/*.AppImage
      - dist_electron/*.deb

Build MacOS:
  script:
    - source ~/.zshrc
    - WORKDIR=$(mktemp -d)
    - rsync -r --exclude=.git ./ "$WORKDIR"
    - cd "$WORKDIR"
    - nvm use 14
    - npm install --no-package-lock --registry=https://nexus.barrage.net/repository/npm.barrage.net/ --username=gitlab-ci-readonly --password=$CI_NEXUS_DOCKER_REGISTRY_READ_ONLY
    - npm run electron:build --mac
    - cd $CI_PROJECT_DIR
    - rsync -r $WORKDIR/dist_electron ./
    - rm -rf "$WORKDIR"
    - nvm use default
  tags:
    - macos-electronjs
  artifacts:
    paths:
      - dist_electron/*.dmg
      - dist_electron/*.pkg

Build Windows:
  script:
    - $workdir = Join-Path $Env:Temp $(New-Guid); New-Item -Type Directory -Path $workdir | Out-Null
    - Copy-Item -Path .\* -Destination "$workdir" -PassThru -Recurse -Exclude @(".git")
    - cd "$workdir"
    # - nvm use 14.17.1
    - npm install --no-package-lock
    - npm run electron:build --windows
    - cd "$CI_PROJECT_DIR"
    - Copy-Item -Path "$workdir\dist_electron\*" -Destination ".\" -PassThru -Recurse
    - Remove-Item -Recurse -Force "$workdir"
    # - nvm use default
  tags:
    - windows
  artifacts:
    paths:
      - dist_electron/*.msi
