#!/bin/bash
# . "$(dirname "$0")/_/husky.sh"

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|vue)$')

if [[ "$STAGED_FILES" = "" ]]; then
  echo "No staged files."
  exit 0
fi

#npm run prettier-format
# npx prettier --config .prettierrc 'src/**/*.{js,vue}' --write 

for FILE in $STAGED_FILES
do
#   echo "$FILE"
  npx prettier --config .prettierrc $FILE --write

  if [[ "$?" == 0 ]]; then
    echo "\tLinting file: $FILE"
  else
    echo "\tLint failed for file: $FILE"
    PASS=false
  fi
done

if ! $PASS; then
  echo "Your commit contains files that should pass ESLint but do not. Please fix the lint errors and try again.\n"
  exit 1
# else
#   echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
